---
- include: rpi_setup.yml
  tags:
    - rpi_setup

- include: pihole.yml
  when: pihole_enable
  tags:
    - pihole

- include: docker.yml
  when: monitoring_enable
  tags:
    - docker

- include: uptime.yml
  when: monitoring_enable
  tags:
    - uptime
