---
- import_tasks: rpi_setup.yml
  tags:
    - rpi_setup

- import_tasks: pihole.yml
  when: pihole_enable
  tags:
    - pihole

- import_tasks: docker.yml
  when: monitoring_enable
  tags:
    - docker

- import_tasks: uptime.yml
  when: monitoring_enable
  tags:
    - uptime
