---
- name: Synchronize internet-monitoring directory.
  ansible.posix.synchronize:
    src: internet_monitoring
    dest: "{{ config_dir }}/"
    delete: false
    recursive: true
    perms: false
  become: false

- name: Copy templated internet_monitoring files into place.
  template:
    src: templates/{{ item.src }}
    dest: "{{ config_dir }}/internet_monitoring/{{ item.dest }}"
    mode: 0644
  loop:
    - src: grafana_config.monitoring.j2
      dest: grafana/config.monitoring
    - src: prometheus.yml.j2
      dest: prometheus/prometheus.yml
    - src: prometheus_pinghosts.yaml.j2
      dest: prometheus/pinghosts.yaml
  notify: restart internet_monitoring
  become: false

- name: Ensure internet_monitoring environment is running.
  community.docker.docker_compose:
    project_src: "{{ config_dir }}/internet_monitoring/"
    build: false
  become: false
