---
extends: default

yaml-files:
  - "*.yaml"
  - "*.yml"
  - ".yamllint.yml"
  - ".ansible-lint"

ignore: |
  .venv/

rules:
  line-length:
    max: 120
    level: warning
  document-start:
    ignore: |
      .pre-commit-config.yaml
      .github/workflows/*
  truthy:
    ignore: |
      .github/workflows/*
