---
# Location where configuration files will be stored.
config_dir: "~"

# Pi-hole configuration.
pihole_enable: true
pihole_hostname: pihole
pihole_timezone: Asia/Kolkata
pihole_password: "change-this-password"
