---
- name: test connection
  ping:
  tags:
    - ping
    - never

- name: Ensure apt cache is up to date.
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  when:
    - ansible_facts.os_family == "Debian"

- name: Ensure pacman cache is up to date
  community.general.pacman:
    update_cache: true
  when:
    - ansible_facts.os_family == "Archlinux"
